"""Add bidirectional watchlist relationship and notes field

Revision ID: 116e9e120615
Revises: ff35d59a4174
Create Date: 2026-05-07 00:13:42.834348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116e9e120615'
down_revision = 'ff35d59a4174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=280), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
